<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
    <AssemblyTitle>AvaPlayer</AssemblyTitle>
    <VersionPrefix>1.2.2</VersionPrefix>
    <Version>$(VersionPrefix)</Version>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PublishAot>true</PublishAot>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>$(DefineConstants);LINUX_MPRIS;LINUX_WAYLAND</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <DefineConstants>$(DefineConstants);WINDOWS_SMTC</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**" />
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Wayland" Version="12.1.0" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="FluentIcons.Avalonia" Version="2.1.333" />
    <PackageReference Include="JAJ.Packages.MiniAudioEx" Version="3.3.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.0" PrivateAssets="All" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" PrivateAssets="All" />
    <PackageReference Include="HotAvalonia" Version="3.1.4" PrivateAssets="All" />
  </ItemGroup>
</Project>
